### ISSUE TITLE
Add a way to reuse traceur from clappr bundle

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/generator-clappr-plugin#15]
refs #13

**Comment by whadar** [comment]
Can you elaborate a little bit on what you're planning to do so we can send our comments?

**Comment by flavioribeiro** [comment]
Sure @whadar, sorry for being so shallow. [Traceur](https://github.com/google/traceur-compiler/wiki) is the guy who enable us to write code in ES6, it's a [transpiler](http://en.wikipedia.org/wiki/Source-to-source_compiler). We need some code from it even on the final bundle, and here's the problem. 

On Clappr itself we already have this code and we don't need to have it again on the standalone plugins. Our target on this issue is search for the best way to reuse traceur code inside clappr bundle, avoiding so much code on the plugin and saving a lot of bytes.

**Comment by flavioribeiro** [comment]
Closing this since we're not using traceur anymore.
